/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGeneratePortraitRouteImport } from './routes/api/generate-portrait'
import { Route as ApiUploadCardRouteImport } from './routes/api/upload-card'
import { Route as CIdRouteImport } from './routes/c/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePortraitRoute = ApiGeneratePortraitRouteImport.update({
  id: '/api/generate-portrait',
  path: '/api/generate-portrait',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadCardRoute = ApiUploadCardRouteImport.update({
  id: '/api/upload-card',
  path: '/api/upload-card',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate-portrait': typeof ApiGeneratePortraitRoute
  '/api/upload-card': typeof ApiUploadCardRoute
  '/c/$id': typeof CIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate-portrait': typeof ApiGeneratePortraitRoute
  '/api/upload-card': typeof ApiUploadCardRoute
  '/c/$id': typeof CIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/generate-portrait': typeof ApiGeneratePortraitRoute
  '/api/upload-card': typeof ApiUploadCardRoute
  '/c/$id': typeof CIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/generate-portrait' | '/api/upload-card' | '/c/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/generate-portrait' | '/api/upload-card' | '/c/$id'
  id:
    '__root__' | '/' | '/api/generate-portrait' | '/api/upload-card' | '/c/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGeneratePortraitRoute: typeof ApiGeneratePortraitRoute
  ApiUploadCardRoute: typeof ApiUploadCardRoute
  CIdRoute: typeof CIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-portrait': {
      id: '/api/generate-portrait'
      path: '/api/generate-portrait'
      fullPath: '/api/generate-portrait'
      preLoaderRoute: typeof ApiGeneratePortraitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-card': {
      id: '/api/upload-card'
      path: '/api/upload-card'
      fullPath: '/api/upload-card'
      preLoaderRoute: typeof ApiUploadCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGeneratePortraitRoute: ApiGeneratePortraitRoute,
  ApiUploadCardRoute: ApiUploadCardRoute,
  CIdRoute: CIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
