/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as ApiGeneratePortraitRouteImport } from './routes/api/generate-portrait'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as CIdRouteImport } from './routes/c/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePortraitRoute = ApiGeneratePortraitRouteImport.update({
  id: '/api/generate-portrait',
  path: '/api/generate-portrait',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/themes': typeof ThemesRoute
  '/api/generate-portrait': typeof ApiGeneratePortraitRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/c/$id': typeof CIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/themes': typeof ThemesRoute
  '/api/generate-portrait': typeof ApiGeneratePortraitRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/c/$id': typeof CIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/themes': typeof ThemesRoute
  '/api/generate-portrait': typeof ApiGeneratePortraitRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/c/$id': typeof CIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/themes'
    | '/api/generate-portrait'
    | '/api/uploadthing'
    | '/c/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/studio'
    | '/themes'
    | '/api/generate-portrait'
    | '/api/uploadthing'
    | '/c/$id'
  id:
    | '__root__'
    | '/'
    | '/studio'
    | '/themes'
    | '/api/generate-portrait'
    | '/api/uploadthing'
    | '/c/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRoute
  ThemesRoute: typeof ThemesRoute
  ApiGeneratePortraitRoute: typeof ApiGeneratePortraitRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  CIdRoute: typeof CIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-portrait': {
      id: '/api/generate-portrait'
      path: '/api/generate-portrait'
      fullPath: '/api/generate-portrait'
      preLoaderRoute: typeof ApiGeneratePortraitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRoute,
  ThemesRoute: ThemesRoute,
  ApiGeneratePortraitRoute: ApiGeneratePortraitRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  CIdRoute: CIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
